#I'm new to rust so for referencing later: https://doc.rust-lang.org/cargo/reference/profiles.html

# [Table]
# key = {inline table}

# A table is just a named section that Cargo knows what to do with. Everything underneath is a key which may 
# be specified further with fields {which go in an inline table if there are multiple for one key}
# Tables can have nested tables eg. [dependencies.embassy-time] is a table nested in [dependencies] 

[workspace]
members = [
    "flight", 
    "maths", 
    "control"]

resolver = "2"

[workspace.dependencies]
libm = "0.2"
defmt = "1"
defmt-rtt = "1"
panic-probe = { version = "1", features = ["print-defmt"] }
cortex-m = { version = "0.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7"

embassy-executor = { version = "0.7", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.4", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-sync = { version = "0.7", features = ["defmt"] }
embassy-stm32 = { version = "0.2", features = ["defmt", "unstable-pac", "memory-x", "exti", "time-driver-any"] }

[profile.release]
opt-level = 1 # This is like C++ -O1 optimisation flag 
lto = "thin" # link-time optimisation, allows optimisation across crates rather than "optimise everything separately, then link"
codegen-units = 1 # don't let the compiler split crates into chunks, force it to optimise everything together
panic = "abort" # runtime errors just stop the programme instead of unwinding the stack 


# Override for a specific crate
[profile.release.package.maths]
opt-level = 3

[profile.release.package.control]
opt-level = 2

[profile.release.package.flight]
opt-level = "z"